services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: tonsnoei/photon-geocoder:latest
    volumes:
      - /home/user/photon/data:/photon/photon_data
    ports:
      - 2322:2322
